name: cndi
on:
  push:
    branches:
      - main
      - "releases/**"
jobs:
  cndi-run:
    runs-on: ubuntu-20.04
    steps:
      - name: welcome
        run: echo "welcome to cndi!"
      
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup cndi
        uses: polyseam/setup-cndi@1.0.3
        with:
          version: state-hack

      - name: cndi chmod
        run: chmod +x bin/cndi # make cndi cli executable

      - name: cndi install
        run: bin/cndi install # run 'cndi install'

      # this next step is the core of the workflow
      - name: cndi run
        env:
          GIT_REPO: https://github.com/${{ github.repository}}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          TERRAFORM_STATE_PASSPHRASE: ${{ secrets.TERRAFORM_STATE_PASSPHRASE }}
          ARGO_UI_READONLY_PASSWORD: ${{ secrets.ARGO_UI_READONLY_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SEALED_SECRETS_PRIVATE_KEY_MATERIAL: ${{ secrets.SEALED_SECRETS_PRIVATE_KEY_MATERIAL }}
          SEALED_SECRETS_PUBLIC_KEY_MATERIAL: ${{ secrets.SEALED_SECRETS_PUBLIC_KEY_MATERIAL }}
        run: bin/cndi run # run 'cndi run'
