name: 'AWS: Deploy Airflow CNDI Cluster Nightly'

on:
  schedule:
    - '0 4 * 12 *' # we will change this when we are ready to run this nightly
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create Test Repo'
        run: 'gh repo create polyseam/aws-active-cndi-test --private --clone'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Checkout Test Repo'
        uses: actions/checkout@v2
        with:
          repository: polyseam/aws-active-cndi-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: aws-active-cndi-test

      - name: Deno 
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

      - name: setup cndi
        uses: polyseam/setup-cndi@v2.0.0

      - name: cndi install
        run: cndi install

      - name: cndi init
        run: cndi init -t https://raw.githubusercontent.com/polyseam/cndi-e2e-test-templates/main/aws/airflow-e2e.jsonc
      
      # replace all placeholders in .env with secrets
      - name: rewrite AWS_REGION .env
        run: sed -i "s/AWS_REGION_PLACEHOLDER__/us-east-1" .env

      - name: rewrite AWS_ACCESS_KEY_ID .env
        run: sed -i "s/AWS_ACCESS_KEY_ID_PLACEHOLDER__/${{ secrets.AWS_ACCESS_KEY_ID }}" .env

      - name: rewrite AWS_SECRET_ACCESS_KEY .env
        run: sed -i "s/AWS_SECRET_ACCESS_KEY_PLACEHOLDER__/${{ secrets.AWS_SECRET_ACCESS_KEY }}" .env

      - name: rewrite GIT_USERNAME .env
        run: sed -i "s/GIT_USERNAME_PLACEHOLDER__/${{ secrets.GIT_USERNAME }}" .env

      - name: rewrite GIT_PASSWORD .env
        run: sed -i "s/GIT_PASSWORD_PLACEHOLDER__/${{ secrets.GIT_PASSWORD }}" .env
        
      - name: rewrite GIT_REPO .env
        run: sed -i "s/GIT_REPO_PLACEHOLDER__/https:\/\/github.com\/polyseam\/aws-active-cndi-test" .env

      - name: set secrets
        run: gh secrets set -f .env

      - name: set secrets again
        run: gh secrets set -f .env

      - name: set secrets again again
        run: gh secrets set -f .env
      
      - name: stage files
        run: git add .
      
      - name: commit files
        run: git commit -m "deploy test cluster for aws - $NOW"
      
      - name: push files
        run: git push origin main