name: 'AWS: Deploy Airflow CNDI Cluster Nightly'

on:
  schedule:
    - '0 4 * 12 *' # we will change this when we are ready to run this nightly
jobs:
  build:
    # env:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: 'install gh'

        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: 'Delete Test Repo'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: 'gh repo delete polyseam-e2e/aws-airflow-cndi-e2e --yes'

      - name: 'Create Test Repo'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: 'gh repo create polyseam-e2e/aws-airflow-cndi-e2e --private --clone --add-readme'

      - name: 'Checkout Test Repo'
        uses: actions/checkout@v2
        with:
          repository: polyseam-e2e/aws-airflow-cndi-e2e
          token: ${{ secrets.GH_TOKEN }}
          # path: aws-airflow-cndi-e2e
      
      - name: echo hi
        run: echo hi

      - name: Deno 
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

      - name: setup cndi
        uses: polyseam/setup-cndi@v2.0.0

      - name: cndi install
        run: cndi install

      - name: cndi init
        run: cndi init -t https://raw.githubusercontent.com/polyseam/cndi-e2e/main/templates/aws/airflow-e2e.jsonc
      
      # replace all placeholders in .env with secrets
      - name: rewrite AWS_REGION .env
        run: sed -i "s/AWS_REGION_PLACEHOLDER__/us-east-1" .env

      - name: rewrite AWS_ACCESS_KEY_ID .env
        run: sed -i "s/AWS_ACCESS_KEY_ID_PLACEHOLDER__/${{ secrets.AWS_ACCESS_KEY_ID }}" .env

      - name: rewrite AWS_SECRET_ACCESS_KEY .env
        run: sed -i "s/AWS_SECRET_ACCESS_KEY_PLACEHOLDER__/${{ secrets.AWS_SECRET_ACCESS_KEY }}" .env

      - name: rewrite GIT_USERNAME .env
        run: sed -i "s/GIT_USERNAME_PLACEHOLDER__/${{ secrets.GIT_USERNAME }}" .env

      - name: rewrite GIT_PASSWORD .env
        run: sed -i "s/GIT_PASSWORD_PLACEHOLDER__/${{ secrets.GIT_PASSWORD }}" .env
        
      - name: rewrite GIT_REPO .env
        run: sed -i "s/GIT_REPO_PLACEHOLDER__/https:\/\/github.com\/polyseam-e2e\/aws-airflow-cndi-e2e" .env

      - name: set secrets
        run: gh secrets set -f .env

      - name: set secrets again
        run: gh secrets set -f .env

      - name: set secrets again again
        run: gh secrets set -f .env
      
      - name: stage files
        run: git add .
      
      - name: commit files
        run: git commit -m "deploy test cluster for aws - $NOW"
      
      - name: push files
        run: git push origin main