name: Build and Release for GitHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deno 
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: deno task test

      - name: Get version from deno.json
        uses: polyseam/get-version-from-package-json@v.1.0.0
        id: get_deno_json
        with:
          path-to-file: './deno.json'
      
      - name: Compare Git Tag to CNDI Version
        if: ${{ steps.get_deno_json.outputs.version != github.ref_name }}
        run: | 
          echo "CNDI Version: ${{ steps.get_deno_json.outputs.version }} does not match Tag version: ${{ github.ref_name }}" && exit 1

      - name: Build
        run: deno task build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            dist/cndi-*